name: Deploy Next.js static site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: next

      - name: Create env.js from GH Pages environment vars
        run: |
          : > next/public/env.js
          echo "window.__ENV__ = {" >> next/public/env.js
          if [ -n "${{ secrets.FORMSPREE_ACTION_URL }}" ]; then echo "  NEXT_PUBLIC_FORMSPREE_ACTION_URL: '${{ secrets.FORMSPREE_ACTION_URL }}'," >> next/public/env.js; fi
          if [ -n "${{ vars.SITE_URL }}" ]; then echo "  NEXT_PUBLIC_SITE_URL: '${{ vars.SITE_URL }}'" >> next/public/env.js; fi
          echo "};" >> next/public/env.js

      - name: Build
        run: npm run build
        working-directory: next

      - name: Export static site
        run: npm run export
        working-directory: next

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: next/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

